import { createHash } from 'node:crypto';

// Everyday A2–B1 exercises, shuffled without repeats within each cycle.
export const builtinPairs = [
  ['오늘은 평소보다 조금 일찍 일어났어요.', 'I woke up a little earlier than usual today.'],
  ['퇴근하고 집에 가는 길에 우유를 사야 해요.', 'I need to buy some milk on my way home from work.'],
  ['비가 그치면 잠깐 산책하러 갈 거예요.', 'I will go for a short walk when the rain stops.'],
  ['이 카페는 커피도 맛있고 분위기도 좋아요.', 'This cafe has good coffee and a nice atmosphere.'],
  ['주말에는 알람 없이 늦게까지 자고 싶어요.', 'I want to sleep in without an alarm this weekend.'],
  ['어제 본 영화가 생각보다 재미있었어요.', 'The movie I watched yesterday was more fun than I expected.'],
  ['저녁으로 뭘 먹을지 아직 못 정했어요.', 'I have not decided what to have for dinner yet.'],
  ['버스를 놓쳐서 회사에 조금 늦었어요.', 'I missed the bus, so I was a little late for work.'],
  ['이 셔츠를 다른 사이즈로 바꿀 수 있을까요?', 'Could I exchange this shirt for a different size?'],
  ['휴대폰 배터리가 거의 다 떨어졌어요.', 'My phone battery is almost dead.'],
  ['시간이 괜찮으면 내일 점심 같이 먹을래요?', 'Would you like to have lunch together tomorrow if you have time?'],
  ['요즘 자기 전에 책을 조금씩 읽고 있어요.', 'These days, I read a little before going to bed.'],
  ['이 길로 쭉 가면 왼쪽에 약국이 있어요.', 'If you go straight down this street, there is a pharmacy on your left.'],
  ['집 열쇠를 어디에 뒀는지 기억이 안 나요.', 'I cannot remember where I put my house keys.'],
  ['너무 피곤해서 오늘은 일찍 자려고 해요.', 'I am so tired that I am going to bed early tonight.'],
  ['이 음식에 땅콩이 들어 있나요?', 'Does this dish contain peanuts?'],
  ['친구가 추천해 준 식당에 가 봤어요.', 'I tried the restaurant my friend recommended.'],
  ['회의 시작 시간을 한 시간 늦출 수 있을까요?', 'Could we move the start of the meeting back by an hour?'],
  ['창문을 열어도 괜찮을까요?', 'Would it be okay if I opened the window?'],
  ['다음 달에 처음으로 혼자 여행을 가요.', 'I am traveling alone for the first time next month.'],
  ['생각보다 사람이 많아서 놀랐어요.', 'I was surprised that there were more people than I expected.'],
  ['이번 주는 일이 많아서 운동을 못 했어요.', 'I could not exercise this week because I had a lot of work.'],
  ['천천히 다시 한번 설명해 주시겠어요?', 'Could you explain that again slowly?'],
  ['어릴 때는 당근을 싫어했지만 지금은 잘 먹어요.', 'I did not like carrots as a child, but I eat them now.'],
  ['비가 올 것 같으니 우산을 챙기세요.', 'It looks like it is going to rain, so take an umbrella.'],
  ['주문한 음식이 아직 안 나왔어요.', 'The food I ordered has not arrived yet.'],
  ['오늘 해야 할 일을 거의 다 끝냈어요.', 'I have finished almost everything I need to do today.'],
  ['여기서 사진 한 장 찍어 주실 수 있나요?', 'Could you take a photo of me here?'],
  ['이 신발은 예쁘지만 오래 걸으면 발이 아파요.', 'These shoes look nice, but my feet hurt when I walk in them for a long time.'],
  ['방 청소를 하다가 오래된 사진을 찾았어요.', 'I found an old photo while cleaning my room.'],
  ['약속 장소에 도착하면 전화해 주세요.', 'Please call me when you arrive at our meeting place.'],
  ['지금 출발하면 기차를 탈 수 있을 거예요.', 'If we leave now, we should be able to catch the train.'],
  ['처음에는 어려웠지만 점점 익숙해지고 있어요.', 'It was difficult at first, but I am getting used to it.'],
  ['오늘은 집에서 아무것도 안 하고 쉬고 싶어요.', 'I just want to stay home and relax today.'],
  ['장 보러 가기 전에 냉장고를 확인해 보세요.', 'Check the fridge before you go grocery shopping.'],
  ['일주일에 세 번은 직접 요리하려고 노력해요.', 'I try to cook for myself three times a week.'],
  ['음악 소리를 조금만 줄여 주시겠어요?', 'Could you turn the music down a little?'],
  ['답장이 늦어서 미안해요. 이제 메시지를 봤어요.', 'Sorry for the late reply. I just saw your message.'],
  ['이번 여행에서 가장 좋았던 곳은 어디였어요?', 'What was your favorite place on this trip?'],
  ['매일 조금씩 연습하면 더 나아질 거예요.', 'You will get better if you practice a little every day.'],
  ['저는 보통 지하철을 타고 출근해요.', 'I usually take the subway to work.'],
  ['오늘 아침에는 너무 바빠서 아침을 못 먹었어요.', 'I was too busy to have breakfast this morning.'],
  ['빨래가 아직 마르지 않아서 밖에 걸어 두었어요.', 'The laundry is not dry yet, so I left it hanging outside.'],
  ['내일 아침에 쓰레기를 내다 버리는 것을 잊지 마세요.', 'Do not forget to take out the trash tomorrow morning.'],
  ['설거지는 제가 할 테니 식탁을 치워 주시겠어요?', 'I will wash the dishes. Could you clear the table?'],
  ['오늘은 날씨가 좋아서 걸어서 출근했어요.', 'The weather was nice today, so I walked to work.'],
  ['저는 커피보다 차를 더 좋아해요.', 'I prefer tea to coffee.'],
  ['평일에는 보통 여섯 시 반에 일어나요.', 'I usually get up at six thirty on weekdays.'],
  ['저는 점심을 먹은 후에 항상 이를 닦아요.', 'I always brush my teeth after lunch.'],
  ['집을 나서기 전에 불을 모두 껐는지 확인했어요.', 'I checked that all the lights were off before leaving home.'],
  ['이 사과는 저 사과보다 더 달아요.', 'This apple is sweeter than that one.'],
  ['이 재킷은 너무 비싸서 살 수 없어요.', 'This jacket is too expensive for me to buy.'],
  ['이 가방은 제 노트북이 들어갈 만큼 커요.', 'This bag is big enough to fit my laptop.'],
  ['현금 대신 카드로 결제해도 되나요?', 'Can I pay by card instead of cash?'],
  ['선물할 거라서 포장해 주시면 좋겠어요.', 'It is a gift, so I would like you to wrap it.'],
  ['영수증을 이메일로 보내 주실 수 있나요?', 'Could you email me the receipt?'],
  ['저는 목록에 있는 것만 사려고 했어요.', 'I was only planning to buy the things on my list.'],
  ['이 신발을 신어 볼 수 있을까요?', 'Could I try these shoes on?'],
  ['이 가게는 일요일마다 문을 닫아요.', 'This store is closed every Sunday.'],
  ['온라인으로 주문한 책이 오늘 도착했어요.', 'The book I ordered online arrived today.'],
  ['가장 가까운 지하철역까지 걸어서 얼마나 걸리나요?', 'How long does it take to walk to the nearest subway station?'],
  ['다음 정류장에서 내려야 해요.', 'I need to get off at the next stop.'],
  ['서울로 가는 표 두 장 주세요.', 'Two tickets to Seoul, please.'],
  ['이 버스가 공항에 가나요?', 'Does this bus go to the airport?'],
  ['교통이 막혀서 평소보다 삼십 분 더 걸렸어요.', 'The traffic was heavy, so it took thirty minutes longer than usual.'],
  ['길을 잘못 들어서 다시 돌아가야 했어요.', 'I took a wrong turn and had to go back.'],
  ['안전벨트를 매고 나서 출발해 주세요.', 'Please wait until I put on my seat belt before you start driving.'],
  ['비행기가 두 시간 연착되었어요.', 'My flight was delayed by two hours.'],
  ['짐이 무거워서 택시를 탔어요.', 'My luggage was heavy, so I took a taxi.'],
  ['이 자리에 앉아도 될까요?', 'May I sit here?'],
  ['두 명이 앉을 자리가 있나요?', 'Do you have a table for two?'],
  ['너무 맵지 않은 음식을 추천해 주시겠어요?', 'Could you recommend something that is not too spicy?'],
  ['제 샌드위치에는 양파를 빼 주세요.', 'Please leave the onions out of my sandwich.'],
  ['물 한 잔 더 주시겠어요?', 'Could I have another glass of water?'],
  ['남은 음식을 포장해 주실 수 있나요?', 'Could you pack up the leftover food for me?'],
  ['저는 배가 별로 고프지 않아서 수프만 주문했어요.', 'I was not very hungry, so I only ordered soup.'],
  ['빵을 오븐에서 꺼내기 전에 십 분 더 기다려야 해요.', 'We need to wait ten more minutes before taking the bread out of the oven.'],
  ['냉장고에 계란이 몇 개 남아 있나요?', 'How many eggs are left in the fridge?'],
  ['저는 이 수프에 소금을 너무 많이 넣었어요.', 'I put too much salt in this soup.'],
  ['저녁을 다 먹을 때까지 디저트는 먹지 않을 거예요.', 'I will not have dessert until I finish dinner.'],
  ['이 파일을 오늘 오후까지 보내 주시겠어요?', 'Could you send me this file by this afternoon?'],
  ['회의에 참석하지 못해서 미안해요.', 'I am sorry I could not attend the meeting.'],
  ['저는 방금 보고서 작성을 마쳤어요.', 'I have just finished writing the report.'],
  ['모르는 단어가 있으면 사전에서 찾아보세요.', 'If you do not know a word, look it up in a dictionary.'],
  ['이 문제를 푸는 데 한 시간이 걸렸어요.', 'It took me an hour to solve this problem.'],
  ['저는 작년부터 영어를 배우고 있어요.', 'I have been learning English since last year.'],
  ['컴퓨터가 갑자기 꺼져서 작업한 내용을 잃었어요.', 'My computer suddenly shut down, and I lost my work.'],
  ['수업이 몇 시에 끝나는지 알려 주시겠어요?', 'Could you tell me what time the class ends?'],
  ['저는 조용한 곳에서 공부할 때 집중이 더 잘돼요.', 'I can concentrate better when I study in a quiet place.'],
  ['선생님이 내일까지 숙제를 제출하라고 하셨어요.', 'The teacher told us to hand in our homework by tomorrow.'],
  ['이번 토요일에 우리 집에 놀러 올래요?', 'Would you like to come over to my place this Saturday?'],
  ['친구를 기다리는 동안 커피를 마셨어요.', 'I had some coffee while I was waiting for my friend.'],
  ['우리는 고등학교 때부터 친구예요.', 'We have been friends since high school.'],
  ['도와줘서 고마워요. 덕분에 제시간에 끝냈어요.', 'Thank you for your help. Thanks to you, I finished on time.'],
  ['다음 주에 시간이 되는 날을 알려 주세요.', 'Please let me know which days you are free next week.'],
  ['친구 생일 선물로 무엇을 사야 할지 모르겠어요.', 'I do not know what to buy my friend for their birthday.'],
  ['저는 동생에게 자전거 타는 법을 가르쳐 줬어요.', 'I taught my younger sibling how to ride a bike.'],
  ['어젯밤에 부모님과 한 시간 동안 통화했어요.', 'I talked to my parents on the phone for an hour last night.'],
  ['제가 늦으면 먼저 식사를 시작하세요.', 'If I am late, please start eating without me.'],
  ['오랜만에 친구를 만나서 정말 반가웠어요.', 'I was really happy to see my friend after such a long time.'],
  ['저는 전에 이 도시에 와 본 적이 있어요.', 'I have been to this city before.'],
  ['호텔에 도착했을 때 방이 아직 준비되지 않았어요.', 'My room was not ready yet when I arrived at the hotel.'],
  ['방을 하루 더 사용할 수 있을까요?', 'Could I keep the room for one more night?'],
  ['여기서 바다까지는 차로 이십 분 정도 걸려요.', 'It takes about twenty minutes to drive to the beach from here.'],
  ['박물관은 월요일을 제외하고 매일 열어요.', 'The museum is open every day except Monday.'],
  ['여행을 떠나기 전에 숙소를 예약했어요.', 'I booked a place to stay before leaving for my trip.'],
  ['이곳은 제가 가 본 곳 중에서 가장 조용해요.', 'This is the quietest place I have ever visited.'],
  ['내일 날씨가 좋으면 자전거를 빌릴 거예요.', 'If the weather is nice tomorrow, I will rent a bike.'],
  ['사진을 찍느라 일몰을 제대로 보지 못했어요.', 'I was so busy taking photos that I did not really watch the sunset.'],
  ['다음에는 가족과 함께 이곳에 오고 싶어요.', 'Next time, I would like to come here with my family.'],
  ['어젯밤에 늦게 자서 지금 졸려요.', 'I went to bed late last night, so I am sleepy now.'],
  ['저는 긴장하면 말을 빨리 하는 편이에요.', 'I tend to speak quickly when I am nervous.'],
  ['이 노래를 들으면 어린 시절이 생각나요.', 'This song reminds me of my childhood.'],
  ['저는 예전에는 매일 달렸지만 요즘은 주말에만 달려요.', 'I used to run every day, but now I only run on weekends.'],
  ['어제 빌린 책을 다음 주까지 돌려줘야 해요.', 'I need to return the book I borrowed yesterday by next week.'],
  ['화분에 물을 너무 자주 주지 마세요.', 'Do not water the plant too often.'],
  ['저는 새 취미를 시작할 생각이에요.', 'I am thinking of taking up a new hobby.'],
  ['저는 개와 고양이를 둘 다 좋아해요.', 'I like both dogs and cats.'],
  ['텔레비전을 보고 있는데 초인종이 울렸어요.', 'I was watching television when the doorbell rang.'],
  ['오늘 배운 표현을 내일 다시 연습할 거예요.', 'I will practice the expressions I learned today again tomorrow.'],
];

// Stable content IDs are independent of the order of the shipped collection.
export const builtinExamples = builtinPairs.map(([korean, reference]) => ({
  id: 'builtin-' + createHash('sha256').update(korean).digest('hex').slice(0, 20),
  korean, reference,
}));
